CREATE DATABASE SIRKET
USE SIRKET
CREATE TABLE ISCI(
ID INT PRIMARY KEY IDENTITY,
MKOD NVARCHAR(100),
SAA NVARCHAR(100),
VEZIFEID INT REFERENCES VEZIFE(ID),
MAAS MONEY)
INSERT INTO ISCI VALUES('CODE ACADEMY','RAIL DJANNATOV',1,800)
INSERT INTO ISCI VALUES('CODE ACADEMY','FARIZ ASADOV',1,1200)
SELECT * FROM ISCI

CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
VEZIFE NVARCHAR(100))
INSERT INTO VEZIFE VALUES('MENTOR')
SELECT * FROM VEZIFE

CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
FILIAL NVARCHAR(100))

CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100),
ALISQIYMETI MONEY,
SATISQIYMETI MONEY)

INSERT INTO MEHSUL 
VALUES('DEFTER',10,20),
      ('QELEM',5,15)

SELECT * FROM MEHSUL



CREATE TABLE SATIS(
ID INT PRIMARY KEY IDENTITY,
MEHSULID INT REFERENCES MEHSUL(ID),
ISCIID INT REFERENCES ISCI(ID),
TETBIQOLUNANENDIRIM INT,
SATISTARIXI DATE)

--SORGU1
SELECT COUNT (SAA) FROM ISCI  

--SORGU2
SELECT SAA FROM ISCI ORDER BY MAAS DESC

--SORGU3
SELECT AD FROM MEHSUL ORDER BY SATISQIYMETI DESC

--SORGU4
SELECT * FROM SATIS ORDER BY SATISTARIXI

--SORGU5
SELECT SAA, VEZIFE.VEZIFE
FROM ISCI
INNER JOIN  VEZIFE ON VEZIFEID=VEZIFE.ID



